# Numpy的使用

## ndarray实例

*ndarray在numpy中的别名是array*

np.array()生成一个ndarray数组

np.array()输出成[]形式，元素由空格分开

|属性|说明|
|----|----|
|.ndim|秩，即轴的数量或维度的数量|
|.shape|元组的各个元素分别表示ndarray对象不同轴的长度，对于矩阵，n行m列|
|.size|ndarray对象元素的个数，相当于.shape中的nxm的值|
|.dtype|ndarray对象的元素类型 |
|.itemsize|ndarray对象每个元素的大小，以字节为单位|

In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.ndim,a.shape,a.size,a.dtype,a.itemsize

(2, (2, 3), 6, dtype('int32'), 4)

## ndarray为什么要支持这么多种元素类型而python中仅支持整数，浮点数和复数？
- 科学计算涉及的数据较多，对存储和性能有较高的要求
- 对元素类型精细定义，有助于NumPy合理使用存储空间并优化性能
- 对元素类型精细定义，有助于程序员对程序规模有合理评估

## ndarray数组创建方法
1. 从python中的列表，元组等类型创建ndarray数组
> x = np.array(list/tuple)
> x = np.array(list/tuple,dtype=np.float32)

In [12]:
import numpy as np
np.array([[1,2,3],[4,5,6]])
np.array(((11,22,33),(44,55,66)))
a,b

(array([[1, 2, 3],
        [4, 5, 6]]), array([[11, 22, 33],
        [44, 55, 66]]))

2. 使用NumPy中函数创建ndarray数组，如：arange, ones, zeros等

|函数|说明|
|----|----|
|np.arange(n)|类似range()函数，返回ndarray类型，元素从0到n‐1 |
|np.ones(shape)|根据shape生成一个全1数组，shape是元组类型|
|np.zeros(shape)|根据shape生成一个全0数组，shape是元组类型|
|np.full(shape,val)|根据shape生成一个数组，每个元素值都是val|
|np.eye(n)|创建一个正方的n*n单位矩阵，对角线为1，其余为0|
|***********|***********|
|np.ones_like(a)|根据数组a的形状生成一个全1数组 |
|np.zeros_like(a)|根据数组a的形状生成一个全0数组 |
|np.full_like(a,val)|根据数组a的形状生成一个数组，每个元素值都是val|
|***********|***********|
|np.linspace(n1,n2,n3)|根据起止数据等间距地填充数据，形成数组,n1为生成数组的第一个值，n2为最后一个值，n3为数组中元素的个数，还有一个endpoint的参数，在下面例子中可以看到|
|np.concatenate((a,b,c))|将两个或多个数组合并成一个新的数组,这些数组必须形成一个元组才可以合并成一个数组|

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.ones_like([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full_like([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.]],8)

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [21]:
a = np.linspace(1, 10, 4)
b = np.linspace(1,10,4,endpoint=False)
c=np.concatenate((a,b))
a,b,c

(array([ 1.,  4.,  7., 10.]),
 array([1.  , 3.25, 5.5 , 7.75]),
 array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75]))

#### 为什么numpy生成的数为什么默认为浮点数呢？
浮点数用于科学计算

## ndarray数组的变换
对于创建后的ndarray数组，可以对其进行维度变换和元素类型变换
### 数组维度的变换
|方法|说明|
|----|----|
|.reshape(shape)|不改变数组元素，返回一个shape形状的数组，原数组不变 |
|.resize(shape)|与.reshape()功能一致，但修改原数组|
|.swapaxes(ax1,ax2)|将数组n个维度中两个维度进行调换 |
|.flatten()|对数组进行降维，返回折叠后的一维数组，原数组不变|

In [29]:
a=np.ones((2,3,4),dtype=np.int32)
b=a.reshape((3,8))
a,b

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]), array([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]]))

In [40]:
a = np.ones((2, 3, 4), dtype=np.int32)
b=a.resize((3,8))
a,b

(array([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]]), None)

*ndarray.reshape()和ndarray.resize()的区别是：是否改变原数组ndarray的值，reshape不改变原数组的值，所以需要将reshape后的数组返回给新的对象接收，resize改变原数组的值，所以就不需要返回给新的对象接收，这就是为什么`b = a.resize((3,8)`时，b的值是None*

### 数组元素数据类型的转换
`new_a = a.astype(new_type)`
astype()函数肯定会创建新的数组（对原始数据进行拷贝），即使新的数组类型和原来的类型一致

In [47]:
a=np.full((2,3,4),8,dtype=np.int)
a,a.dtype# 可以用int代替具体的int32或者int64

(array([[[8, 8, 8, 8],
         [8, 8, 8, 8],
         [8, 8, 8, 8]],
 
        [[8, 8, 8, 8],
         [8, 8, 8, 8],
         [8, 8, 8, 8]]]), dtype('int32'))

### ndarray数组向python的list转换
ls=a.tolist()

In [5]:
a=np.ones((2,3,4),dtype=np.int)
ls=a.tolist()
a,ls

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 [[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
  [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]])

## ndarray中数组的操作（索引和切片）
- 索引：获取数组中特定位置元素的过程
- 切片：：获取数组元素子集的过程
### 一维数组的索引和切片：与Python的列表类似
对于切片来说a[0:6:2]，0表示切片开始的索引，6表示切片结束的索引（但不包含该索引），2表示切片的步长。

In [12]:
a=np.linspace(0,10,5,dtype=np.int)
a,a[2],a[0:6:2]

(array([ 0,  2,  5,  7, 10]), 5, array([ 0,  5, 10]))

### 多维数组的索引和切片
- 多维数组的索引


In [17]:
a=np.arange(24).reshape((2,3,4))
a,a[1,2,3],a[-1,-2,-3]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), 23, 17)

- 多维数组的切片

*数组几维度，切片结果为几个维度*

a[:,:,:],a[::,::,::],a[:,:,0:5:2],可以看到对于三维数组，切片中有两个逗号将ndarray数组分为三份，第一个部分是对最外层维度的切片，第二个部分是对中间维度的切片，第三个部分是对最内部维度的切片，对于每一个维度来说，其切片就和python中list的切片操作是一样的，所以a[:,:,:]和a[::,::,::]的结果一致，因为切片可以省略步长不写

In [24]:
a=np.arange(24).reshape((2,3,4))
a[:,:,:],a[::,::,::],a[:,:,0:5:2],a[0:2:2,0:3:3,0:4:4]

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), array([[[ 0,  2],
         [ 4,  6],
         [ 8, 10]],
 
        [[12, 14],
         [16, 18],
         [20, 22]]]), array([[[0]]]))

## 数组的运算
### 数组与标量运算
- 数组与标量之间间的运算作用于数组的每一个元素

In [27]:
a=np.arange(0,24,1).reshape((2,3,4))
a,a.mean(),a/a.mean()

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 11.5,
 array([[[0.        , 0.08695652, 0.17391304, 0.26086957],
         [0.34782609, 0.43478261, 0.52173913, 0.60869565],
         [0.69565217, 0.7826087 , 0.86956522, 0.95652174]],
 
        [[1.04347826, 1.13043478, 1.2173913 , 1.30434783],
         [1.39130435, 1.47826087, 1.56521739, 1.65217391],
         [1.73913043, 1.82608696, 1.91304348, 2.        ]]]))

### ndarray的一元函数
> 几乎所有的一元函数都不会修改数组本来的值，而是生成一个新的数组来接收，如果要修改，则将修改的数组重新赋值给原数组

|函数|说明|
|-----|-----|
|np.abs(x) np.fabs(x)|计算数组各元素的绝对值|
|np.sqrt(x)|计算数组各元素的开方根|
|np.square(x)|计算数组各元素的平方|
|np.log(x) np.log10(x) np.log2(x)|计算数组各元素的自然对数，10底对数和2底对数|
|np.ceil(x) np.floor(x)|计算数组各元素的ceiling(不超过元素的整数)值或floor(不小于元素的整数)值|
|np.rint(x)|计算数组各元素的四舍五入值|
|np.modf(x)|将数组各元素的小数和整数部分以两个独立数组形式返回 |
|np.cos(x) np.cosh(x) np.sin(x) np.sinh(x) np.tan(x) np.tanh(x)|计算数组各元素的普通型和双曲型三角函数|
|np.exp(x)|计算各元素的e指数值|
|np.sign(x)|计算数组各元素的符号值，1(+), 0, ‐1(‐)|

### ndarray二元函数
|函数|说明|
|-|-|
|+ ‐* / **|两个数组各元素进行对应运算 |
|np.maximum(x,y) np.fmax() np.minimum(x,y) np.fmin()|元素级的最大值/最小值计算 |
|np.mod(x,y)|元素级的模运算|
|np.copysign(x,y)|将数组y中各元素值的符号赋值给数组x对应元素 |
|> < >= <= == !=|算术比较，产生布尔型数组|

# 第一周第二单元：numpy数据存取与函数
## 数据的csv文件存取
CSV (Comma‐Separated Value,逗号分隔值) 

CSV是一种常见的文件格式，用来存储批量数据
### 数据的csv文件的写入
`np.savetxt(frame, array, fmt='%.18e', delimiter=None)` 
- frame : 文件、字符串或产生器，即为保存文件的名字
- array : 存入文件的数组
- fmt: 写入文件的格式，例如：%d %.2f %.18e
- delimiter : 分割字符串，默认是任何空格,对于csv，我们默认使用","

In [35]:
a=np.arange(100).reshape(5,20)
np.savetxt("a.csv",a,fmt="%d",delimiter=",")

### 数据的csv文件的读取
`np.loadtxt(frame, dtype=np.float, delimiter=None,unpack=False)` 
- frame : 文件、字符串或产生器，即为读取文件的名字
- dtype : 读取数据的类型
- delimiter : 分割字符串，默认是任何空格，对于csv，我们默认使用","
- unpack<sup>?</sup> : 如果True，读入属性将分别写入不同变量

In [33]:
b=np.loadtxt("a.csv",delimiter=",")
c=np.loadtxt("a.csv",dtype=np.int,delimiter=",")
d=np.loadtxt("a.csv",dtype=np.int,delimiter=",",unpack=True)
b,c,d

(array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
         33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
         53., 54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
         73., 74., 75., 76., 77., 78., 79.],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
         93., 94., 95., 96., 97., 98., 99.]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
         36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
         56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
         76, 77, 78, 79],
       

### csv文件的局限性
csv文件只能有效存储一维和二维数组，np.savetxt() np.loadtxt()只能有效存取一维和二维数组

## 任意维度数据存取
下面介绍任意维度的存取，但是任意维度写入的数组从文件中读取出来时无法知道写入的时候该数组的shape，因为写入时只是写入了数据，并没有将数组的元数据保存起来，所以可以用到numpy中提供的numpy.save()和numpy.load(),这两个函数保存了数组的元数据
### 任意维度数据写入
> 注意这里使用的是a.tofile(),别的地方都是np.savetxt(),np.loadtxt(),np.fromfile()

`a.tofile(frame, sep='', format='%s')
`
- frame : 文件、字符串的名字
- sep: 数据分割字符串，如果是空串(空串是引号中间什么都没有，空格都没有，如果是空格，则是以空格为分界)，写入文件为二进制
- format : 写入数据的格式

In [38]:
a=np.arange(100).reshape((5,10,2))
a.tofile("b.dat",sep=",",format="%d")
a.tofile("c.dat",format="%d")# 写入二进制格式

### 任意维度数据的读取
`np.fromfile(frame, dtype=float, count=‐1, sep='')`
- frame : 文件、字符串
- dtype: 读取的数据类型
- count : 读入元素个数，‐1表示读入整个文件
- sep: 数据分割字符串，如果是空串(空串是引号中间什么都没有，空格都没有，如果是空格，则是以空格为分界)写入文件为二进制

In [8]:
b=np.fromfile("b.dat",dtype=np.float,count=-1,sep=",").reshape((5,10,2
            ))
c=np.fromfile("c.dat",dtype=np.int,count=-1,sep="")
b,c

(array([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.]],
 
        [[20., 21.],
         [22., 23.],
         [24., 25.],
         [26., 27.],
         [28., 29.],
         [30., 31.],
         [32., 33.],
         [34., 35.],
         [36., 37.],
         [38., 39.]],
 
        [[40., 41.],
         [42., 43.],
         [44., 45.],
         [46., 47.],
         [48., 49.],
         [50., 51.],
         [52., 53.],
         [54., 55.],
         [56., 57.],
         [58., 59.]],
 
        [[60., 61.],
         [62., 63.],
         [64., 65.],
         [66., 67.],
         [68., 69.],
         [70., 71.],
         [72., 73.],
         [74., 75.],
         [76., 77.],
         [78., 79.]],
 
        [[80., 81.],
         [82., 83.],
         [84., 85.],
         [86., 87.],
         [88., 89.],
         [90., 91.],
         [92., 93.],
 

## Numpy的便捷文件存取
可以很好的解决多维数组问题，因为保存了数组的元数据。
### 便捷文件保存
`np.save(fname, array) 或np.savez(fname, array)`
> 这里的保存格式为.npy

- fname: 文件名，以.npy为扩展名，压缩扩展名为.npz
- array : 数组变量
### 便捷文件读取
`np.load(fname)`
- fname: 文件名，以.npy为扩展名，压缩扩展名为.npz


In [11]:
# 写入文件
a=np.arange(24).reshape(2,3,4)
np.save("d.npy",a)# .npy可加可不加

In [14]:
# 读取写入的文件
b=np.load("d.npy")
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Numpy的随机数函数子库
python中也有random库，是为标量所服务的，而numpy中的random子库，是为多维数组服务的*注意这里是numpy中的字库random库中的函数，所以使用时为`np.random.*`*

`np.random.*`
### Numpy中常用随机函数库
|函数|说明|
|-|-|
|rand(d0,d1,..,dn)|根据d0‐dn创建随机数数组(d0和dn表达的意思是shape，但是不用元组表示)浮点数，[0,1)包含零不包含一，均匀分布|
|randn(d0,d1,..,dn)|根据d0‐dn创建随机数数组(d0和dn表达的意思是shape，但是不用元组表示)，标准正态分布|
|randint(low[,high,shape])|根据shape创建随机整数或整数数组，范围是[low, high),包含low不包含high,如果只是传入一个参数，则是生成一个不小于该参数的整数|
|seed(s)|随机数种子，s是给定的种子值|

In [23]:
import numpy as np
a=np.random.rand(2,3,4)
b=np.random.randn(2,3,4)
c=np.random.randint(5,7,(2,3,4))
np.random.seed(10)


### Numpy中高级随机函数库
|函数|说明|
|-|-|
|shuffle(a)|根据数组a的第1轴进行随排列，改变数组x |
|permutation(a)|根据数组a的第1轴产生一个新的乱序数组，不改变数组x，生成新的数组 |
|choice(a[,size,replace,p])|从一维数组a中以概率p抽取元素，形成size形状新数组 replace表示是否可以重用元素，默认为False|

### Numpy中高级随机函数库（生成特定分布）
|函数|说明|
|-|-|
|uniform(low,high,size)|产生具有均匀分布的数组,low起始值,high结束值,size形状 |
|normal(loc,scale,size)|产生具有正态分布的数组,loc均值,scale标准差,size形状 |
|poisson(lam,size)|产生具有泊松分布的数组,lam随机事件发生率,size形状|

## Numpy中的统计函数
Numpy直接提供的统计函数`np.*`
### 统计函数1
|函数|说明|
|-|-|
|sum(a, axis=None)|根据给定轴axis计算数组a相关元素之和，axis整数或元组|
|mean(a, axis=None)|根据给定轴axis计算数组a相关元素的期望，axis整数或元组|
|average(a,axis=None,weights=None)|根据给定轴axis计算数组a相关元素的加权平均值|
|std(a, axis=None)|根据给定轴axis计算数组a相关元素的标准差|
|var(a, axis=None)|根据给定轴axis计算数组a相关元素的方差|
> 如果axis=None，则是对数组中所有的数据进行运算，如果给定轴的话，则是对轴上的数据进行运算



In [38]:
import numpy as np
a=np.arange(12).reshape(3,4)
print("y轴是0，x轴为1")
a,np.mean(a),np.mean(a,axis=0),np.mean(a,axis=1)

y轴是0，x轴为1


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 5.5,
 array([4., 5., 6., 7.]),
 array([1.5, 5.5, 9.5]))

### 统计函数2
|函数|说明|
|-|-|
|min(a)  max(a)|计算数组a中元素的最小值、最大值|
|argmin(a)  argmax(a)|计算数组a中元素最小值、最大值的对应一维数组下标|
|unravel_index(index, shape)|根据shape将一维下标index转换成多维下标|
|ptp(a)|计算数组a中元素最大值与最小值的差|
|median(a)|计算数组a中元素的中位数（中值）|

In [44]:
import numpy as np
a=np.arange(24,0,-1).reshape(2,3,4)
print(np.argmax(a))# 得到一维数组中最大值的下标
print(np.unravel_index(np.argmax(a),a.shape))# 重塑为多维数组下标
a

0
(0, 0, 0)


array([[[24, 23, 22, 21],
        [20, 19, 18, 17],
        [16, 15, 14, 13]],

       [[12, 11, 10,  9],
        [ 8,  7,  6,  5],
        [ 4,  3,  2,  1]]])

## Numpy中的梯度函数
梯度：连续值之间的变化率，即斜率，适合处理声音图像等连续信号的边缘

梯度的计算：XY坐标轴连续三个X坐标对应的Y轴值：[a, b, c]，其中，b的梯度是：(c‐a)/2
> 对于多维函数来说，每一个维度上对应一个梯度，所以二位函数有两个梯度，三位函数有三个梯度

|函数|说明|
|-|-|
|np.gradient(f)|计算数组f中元素的梯度，当f为多维时，返回每个维度梯度|


In [49]:
import numpy as np
a=np.random.randint(24,size=(4,6))
a,np.gradient(a)

(array([[ 4, 22, 19, 21,  9,  3],
        [ 3, 16, 11,  9, 22, 18],
        [19,  9, 17, 10,  4,  0],
        [21,  0, 10,  8, 17, 13]]),
 [array([[ -1. ,  -6. ,  -8. , -12. ,  13. ,  15. ],
         [  7.5,  -6.5,  -1. ,  -5.5,  -2.5,  -1.5],
         [  9. ,  -8. ,  -0.5,  -0.5,  -2.5,  -2.5],
         [  2. ,  -9. ,  -7. ,  -2. ,  13. ,  13. ]]),
  array([[ 18. ,   7.5,  -0.5,  -5. ,  -9. ,  -6. ],
         [ 13. ,   4. ,  -3.5,   5.5,   4.5,  -4. ],
         [-10. ,  -1. ,   0.5,  -6.5,  -5. ,  -4. ],
         [-21. ,  -5.5,   4. ,   3.5,   2.5,  -4. ]])])

# 第一周第三单元：图像的手绘效果
## 图像的数组表示
图像一般采用RGB三个颜色通道保存颜色，每个通道取值0到255，所以一个像素点有256<sup>3</sup>中颜色，通过三个通道的相互叠加得到各种人类可以识别的颜色.图像可以表示为一个三维数组，首先长宽用两个维度来表示，但是RGB也得用一个唯独表示，空间上可以想象成有三张表个前后排列在一起。
### PIL库（Python Image Library）
PIL库是一个具有强大图像处理能力的第三方库 
`from PIL import Image`
Image是PIL库中代表一个图像的类（对象）

In [56]:
import numpy as np
from PIL import Image
image=np.array(Image.open("C:/Users/PeterLei/Desktop/1.jpg"))
image.shape,image.dtype

((425, 300, 3), dtype('uint8'))

## 图像的变换
图像可以读取为数组，数组可以变换，那么我们就可以对图片进行变换


In [62]:
import numpy as np
from PIL import Image
a=np.array(Image.open("C:/Users/PeterLei/Desktop/1.jpg"))
b=255-a
image=Image.fromarray(b)
image.save("C:/Users/PeterLei/Desktop/2.jpg")

In [64]:
import numpy as np
from PIL import Image
a=np.array(Image.open("C:/Users/PeterLei/Desktop/1.jpg").convert("L"))
b=255-a
image=Image.fromarray(b)
print(b.shape)
image.save("C:/Users/PeterLei/Desktop/2.jpg")

(425, 300)

In [65]:
from PIL import Image
import numpy as np
 
a = np.asarray(Image.open('C:/Users/PeterLei/Desktop/1.jpg').convert('L')).astype('float')
 
depth = 10.                      # (0-100)
grad = np.gradient(a)             #取图像灰度的梯度值
grad_x, grad_y = grad               #分别取横纵图像梯度值
grad_x = grad_x*depth/100.
grad_y = grad_y*depth/100.
A = np.sqrt(grad_x**2 + grad_y**2 + 1.)
uni_x = grad_x/A
uni_y = grad_y/A
uni_z = 1./A
 
vec_el = np.pi/2.2                   # 光源的俯视角度，弧度值
vec_az = np.pi/4.                    # 光源的方位角度，弧度值
dx = np.cos(vec_el)*np.cos(vec_az)   #光源对x 轴的影响
dy = np.cos(vec_el)*np.sin(vec_az)   #光源对y 轴的影响
dz = np.sin(vec_el)              #光源对z 轴的影响
 
b = 255*(dx*uni_x + dy*uni_y + dz*uni_z)     #光源归一化
b = b.clip(0,255)
 
im = Image.fromarray(b.astype('uint8'))  #重构图像
im.save('C:/Users/PeterLei/Desktop/2.jpg')